export const ResponseMessages = {

  LOGIN_SUCCESS: 'Login successful',
  LOGOUT_SUCCESS: 'Logout successful',
  REGISTER_SUCCESS: 'Registration successful',
  OTP_SEND: "OTP sent to email",
  SUCCESS: "Request successful",
  ID_MISSING: "ID parameter is required",
  INVALID_ID: "Invalid ID format.",

  VALIDATION_FAILED: 'Validation failed',
  INVALID_CREDENTIALS: 'Invalid email or password', 
  USER_NOT_FOUND: 'User not found',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  FAILED_TO_MAP:'Failed to map newly created user from database',
  SERVER_ERROR: 'Internal server error',
  UNAUTHORIZED: 'Unauthorized access',
  ACCESS_DENIED: 'Access denied',
  TOO_MANY_REQUESTS:"Too Many Requests",
  JWT_ENV_NOT_SET: "JWT environment variables are not set!",
  USER_ALREADY_VERIFIED: "User already verified",
  USER_NOT_VERIFIED: "User not verified",
  REFRESH_TOKEN_REQUIRED: "Refresh token is required",
  INVALID_OTP: "Invalid or expired OTP",
  RESEND_OTP_SUCCESS: "A new OTP has been sent to your email.",
  INVALID_GOOGLE_TOKEN: "Invalid or expired Google token",
  GOOGLE_SERVICE_ERROR: "Could not connect to Google service",
  GOOGLE_EMAIL_NOT_FOUND: "GOOGLE_EMAIL_NOT_FOUND",
  UNVERIFIED_GOOGLE_EMAIL: "UNVERIFIED_GOOGLE_EMAIL",
  GOOGLE_ACCOUNT_CONFLICT: "GOOGLE_ACCOUNT_CONFLICT",
  REFRESH_TOKEN_INVALID: "Refresh token expired or invalid",

  TOKEN_CREATION_FAILED: "Failed to create password reset token",
  EMAIL_SEND_FAILED: "Failed to send password reset email",
  INVALID_OR_EXPIRED_TOKEN: "Invalid or expired password reset token",
  PASSWORD_RESET_SUCCESS: "Password has been reset successfully",
  TOKEN_NOT_FOUND: "Password reset token not found",
  PASSWORD_SAME_AS_OLD: "New password cannot be the same as the old password",
  PASSWORD_UPDATE_FAILED: "Failed to update password",
  TOKEN_ALREADY_USED: "This password reset token has already been used",
  RESET_LINK_EXPIRED: "Your password reset link has expired",
  RESET_REQUEST_SUCCESS: "Password reset link sent successfully to your email",
  RESET_TOKEN_ALREADY_SENT: "A password reset link has already been sent. Please check your email or try again later.",
}